name: tests

on:
  push:
    branches:
      - devops


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: cd auth && npm ci && npm run test:ci
