name: tests

on:
  push:
    branches:
      - devops


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && cd auth && npm install && npm run test:ci
